# Generated by Django 5.1.7 on 2025-03-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTypingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('date', models.DateField(verbose_name='日付')),
                ('accuracy_rate', models.FloatField(verbose_name='正打率')),
                ('score', models.IntegerField(verbose_name='スコア')),
                ('rank', models.CharField(blank=True, max_length=10, verbose_name='ランク')),
            ],
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='study_time',
            field=models.FloatField(verbose_name='勉強時間'),
        ),
    ]
