# Generated by Django 5.1.7 on 2025-03-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mytypingrecord_alter_studyrecord_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytypingrecord',
            name='idx',
        ),
    ]
