# Generated by Django 5.1.7 on 2025-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_mytypingrecord_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sushida5000Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('accuracy_rate', models.FloatField(verbose_name='正打率')),
                ('score', models.IntegerField(verbose_name='スコア')),
                ('rank', models.CharField(blank=True, max_length=10, verbose_name='ランク')),
            ],
        ),
    ]
