# Generated by Django 5.1.7 on 2025-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sushida10000record'),
    ]

    operations = [
        migrations.AddField(
            model_name='sushida5000record',
            name='correct_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sushida5000record',
            name='mistake_key',
            field=models.IntegerField(default=0),
        ),
    ]
