# Generated by Django 5.1.7 on 2025-03-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sushida5000record_correct_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushida5000record',
            name='accuracy_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='正打率'),
        ),
        migrations.AlterField(
            model_name='sushida5000record',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='スコア'),
        ),
    ]
