# Generated by Django 5.1.7 on 2025-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_sushida5000record_accuracy_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sushida10000record',
            name='correct_key',
            field=models.IntegerField(default=0, verbose_name='正打キー'),
        ),
        migrations.AddField(
            model_name='sushida10000record',
            name='mistake_key',
            field=models.IntegerField(default=0, verbose_name='ミスキー'),
        ),
        migrations.AlterField(
            model_name='sushida10000record',
            name='accuracy_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='正打率'),
        ),
        migrations.AlterField(
            model_name='sushida10000record',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='スコア'),
        ),
        migrations.AlterField(
            model_name='sushida5000record',
            name='correct_key',
            field=models.IntegerField(default=0, verbose_name='正打キー'),
        ),
        migrations.AlterField(
            model_name='sushida5000record',
            name='mistake_key',
            field=models.IntegerField(default=0, verbose_name='ミスキー'),
        ),
    ]
